# Generated by Django 6.0.5 on 2026-05-13 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("uf", models.CharField(max_length=2)),
                ("endereco_sede", models.CharField(blank=True, max_length=200)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("avulso", "Avulso"),
                            ("diario", "Diário"),
                            ("semanal", "Semanal"),
                            ("mensal", "Mensal"),
                            ("anual", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duracao_dias", models.PositiveSmallIntegerField()),
                (
                    "janela_integracao_minutos",
                    models.PositiveSmallIntegerField(default=60),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("endereco", models.CharField(blank=True, max_length=200)),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmpresaTransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razao_social", models.CharField(max_length=200)),
                ("nome_fantasia", models.CharField(blank=True, max_length=150)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("endereco", models.CharField(blank=True, max_length=200)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empresas",
                        to="bilhetagem.municipio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificacao", models.CharField(max_length=50, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("parada", "Parada"),
                            ("onibus", "Ônibus"),
                            ("trem", "Trem"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transportes",
                        to="bilhetagem.empresatransporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_compra", models.DateTimeField(auto_now_add=True)),
                ("valor_pago", models.DecimalField(decimal_places=2, max_digits=8)),
                ("data_validade", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("expirado", "Expirado"),
                            ("cancelado", "Cancelado"),
                            ("consumido", "Consumido"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="bilhetagem.tipoticket",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="bilhetagem.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Validador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("cartao", "Cartão"), ("celular", "Celular")],
                        max_length=20,
                    ),
                ),
                ("data_instalacao", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                (
                    "transporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validadores",
                        to="bilhetagem.transporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Validacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("dentro_janela_integracao", models.BooleanField(default=False)),
                (
                    "valor_debitado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validacoes",
                        to="bilhetagem.ticket",
                    ),
                ),
                (
                    "transporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validacoes",
                        to="bilhetagem.transporte",
                    ),
                ),
                (
                    "validador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validacoes",
                        to="bilhetagem.validador",
                    ),
                ),
            ],
        ),
    ]
